In [37]:
# Ejercicio 1
import pandas as pd
data = {"x": [15, -14, 13, -12, 11, 10, 9, -8, 7, -6, 5, -4, 3, -2, 1], "y": [-1, 2, -3, 4, 5, 6, -7, 8, -9, 10, -11, 12, -13, 14, -15]}
points = pd.DataFrame(data= data)
points

     x   y
0   15  -1
1  -14   2
2   13  -3
3  -12   4
4   11   5
5   10   6
6    9  -7
7   -8   8
8    7  -9
9   -6  10
10   5 -11
11  -4  12
12   3 -13
13  -2  14
14   1 -15

In [ ]:
# Ejercicio 2
points[points["x"]>0]

     x   y
0   15  -1
2   13  -3
4   11   5
5   10   6
6    9  -7
8    7  -9
10   5 -11
12   3 -13
14   1 -15

In [ ]:
# Ejercicio 3
points.query("y < 0")

     x   y
0   15  -1
2   13  -3
6    9  -7
8    7  -9
10   5 -11
12   3 -13
14   1 -15

In [ ]:
# Ejercicio 4
points.query("x > 0 and y > 0")

    x  y
4  11  5
5  10  6

In [ ]:
# Ejercicio 5
for i in range(15):
    for j in range(1):
        if points.iloc[i,0+j] > 0 and points.iloc[i,1+j] > 0:
            print("El punto ({} , {}) sí pertenece al primer cuadrante".format(points.iloc[i,0+j], points.iloc[i,1+j]))
        else:
            print("El punto ({} , {}) no pertenece al primer cuadrante".format(points.iloc[i,0+j], points.iloc[i,1+j]))

El punto (15 , -1) no pertenece al primer cuadrante
El punto (-14 , 2) no pertenece al primer cuadrante
El punto (13 , -3) no pertenece al primer cuadrante
El punto (-12 , 4) no pertenece al primer cuadrante
El punto (11 , 5) sí pertenece al primer cuadrante
El punto (10 , 6) sí pertenece al primer cuadrante
El punto (9 , -7) no pertenece al primer cuadrante
El punto (-8 , 8) no pertenece al primer cuadrante
El punto (7 , -9) no pertenece al primer cuadrante
El punto (-6 , 10) no pertenece al primer cuadrante
El punto (5 , -11) no pertenece al primer cuadrante
El punto (-4 , 12) no pertenece al primer cuadrante
El punto (3 , -13) no pertenece al primer cuadrante
El punto (-2 , 14) no pertenece al primer cuadrante
El punto (1 , -15) no pertenece al primer cuadrante

In [36]:
# Ejercicio 6
word = ["euro", "diez", "algas", "broma", "cicuta", "fatiga", "nachos", "jadeos", "hazañas", "boutique"]
vowels = []
consonants = []
length = []
for e in word:
    length.append(len(e))
    vowel = 0
    cons = 0
    for i in range(len(e)):
        if e[i] == "a" or e[i] == "e" or e[i] == "i" or e[i] == "o" or e[i] == "u":
            vowel += 1
        else:
            cons +=1 
    vowels.append(vowel)
    consonants.append(cons)
data = {"WORD": word}
words = pd.DataFrame(data)
words.insert(loc = 1, column = "LENGTH", value = length)
words.insert(loc = 2, column = "VOWELS", value = vowels)
words.insert(loc = 3, column = "CONSONANTS", value = consonants)
words

       WORD  LENGTH  VOWELS  CONSONANTS
0      euro       4       3           1
1      diez       4       2           2
2     algas       5       2           3
3     broma       5       2           3
4    cicuta       6       3           3
5    fatiga       6       3           3
6    nachos       6       2           4
7    jadeos       6       3           3
8   hazañas       7       3           4
9  boutique       8       5           3

In [45]:
# Ejercicio 7
for i in range(len(words)):
    if words.iloc[i, 2] == 1:
        print(f"La palabra {words.iloc[i,0]} tiene {words.iloc[i,1]} letras de las cuales {words.iloc[i,2]} es vocal y {words.iloc[i,3]} consonantes.")
    elif words.iloc[i, 3] == 1:
        print(f"La palabra {words.iloc[i,0]} tiene {words.iloc[i,1]} letras de las cuales {words.iloc[i,2]} son vocales y {words.iloc[i,3]} consonante.")
    else:
        print(f"La palabra {words.iloc[i,0]} tiene {words.iloc[i,1]} letras de las cuales {words.iloc[i,2]} son vocales y {words.iloc[i,3]} consonantes.")

La palabra euro tiene 4 letras de las cuales 3 son vocales y 1 consonante.
La palabra diez tiene 4 letras de las cuales 2 son vocales y 2 consonantes.
La palabra algas tiene 5 letras de las cuales 2 son vocales y 3 consonantes.
La palabra broma tiene 5 letras de las cuales 2 son vocales y 3 consonantes.
La palabra cicuta tiene 6 letras de las cuales 3 son vocales y 3 consonantes.
La palabra fatiga tiene 6 letras de las cuales 3 son vocales y 3 consonantes.
La palabra nachos tiene 6 letras de las cuales 2 son vocales y 4 consonantes.
La palabra jadeos tiene 6 letras de las cuales 3 son vocales y 3 consonantes.
La palabra hazañas tiene 7 letras de las cuales 3 son vocales y 4 consonantes.
La palabra boutique tiene 8 letras de las cuales 5 son vocales y 3 consonantes.

In [47]:
# Ejercicio 8
words.query("VOWELS == CONSONANTS")

     WORD  LENGTH  VOWELS  CONSONANTS
1    diez       4       2           2
4  cicuta       6       3           3
5  fatiga       6       3           3
7  jadeos       6       3           3

In [49]:
# Ejercicio 9
words.sort_values(by = "LENGTH", ascending = False)

       WORD  LENGTH  VOWELS  CONSONANTS
9  boutique       8       5           3
8   hazañas       7       3           4
4    cicuta       6       3           3
5    fatiga       6       3           3
6    nachos       6       2           4
7    jadeos       6       3           3
2     algas       5       2           3
3     broma       5       2           3
0      euro       4       3           1
1      diez       4       2           2

In [60]:
# Ejercicio 10
column_vowels = words["VOWELS"].tolist()
column_vowels = sorted(column_vowels, reverse = True)
column_vowels

[5, 3, 3, 3, 3, 3, 2, 2, 2, 2]